---
jupyter:
  jupytext:
    formats: ipynb,Rmd
    text_representation:
      extension: .Rmd
      format_name: rmarkdown
      format_version: '1.2'
      jupytext_version: 1.10.0
  kernelspec:
    display_name: Python 3
    language: python
    name: python3
---

```{python}
notebook_fiducia = "Acciones colombia"
notebook_filename = "/data/valores_bancolombia/renta_variable_colombia.csv"
notebook_serie_name = "valor unidad"
```

```{python}
notebook_execution_date = "2020-11-29"
notebook_output_suffix = "2nd_variation__"
```

```{python}

```

```{python}

```

```{python}
import numpy as np
import pandas as pd
```

```{python}
from bancolombia.valores import *
from financial_ml.core import *
```

```{python}

```

```{python}
import os
import dotenv
dotenv.load_dotenv()
repo = os.environ.get('REPO')
```

```{python}
date_suffix = notebook_execution_date

notebook_filename = repo + notebook_filename
print(notebook_filename)
```

```{python}

```

```{python}

```

# EDA ANALISIS

```{python}
investors_builder = ValoresBancolombiaCSV(notebook_filename, notebook_serie_name)
```

```{python}
timeserie = investors_builder.build(notebook_fiducia)
timeserie.to_df().head()
```

## Timeserie exploration

The input CSV file has 3 relevan columns, this notebook explores the statistical properties of one of the columns

```{python}
MSG = """
The timeserie for {name} has {size} point with a this 1d period.
"""

print(MSG.format(
    name=notebook_serie_name,
    size=timeserie.to_df().shape[0]
))
```

### This is a report of the timeserie

it starts by plotting the serie as a function of time, then it proceds to use boxplots to visualize the statistical properties by unit of time.

Finally it models the points in the serie as independet samples and checks the statistical properties, it differentiates the serie to check if there is an improvement.

```{python}
PyplotTimeSerie().plot(timeserie)
```

### Differentiated report

The idea is that the points are not corretaled to each other, this is done to sample morre easily. If there is too much correlation you might try differentiating the time serie.

```{python}
differentiated = Differentitator().transform(timeserie)
PyplotTimeSerie().plot(differentiated)
```

```{python}

```

### 2nd differentiation

The points after the differentitating are still correlated.

```{python}
variations_differences = Differentitator().transform(differentiated)
PyplotTimeSerie().plot(variations_differences)
```

```{python}

```
